name: Codespell

on: push

permissions:
  contents: read

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Codespell
      uses: codespell-project/actions-codespell@v2

env:
  PIP_INDEX_URL: https://pypi-wayback-449168051873.europe-west3.run.app/2023-11-16
  UV_INDEX_URL: https://pypi-wayback-449168051873.europe-west3.run.app/2023-11-16
